gems:
  - jekyll-sitemap

# Outputting
permalink: pretty

# custom vars
# excerpt: Simplify. Integrate. Track.  Simplify electronic proof of delivery (ePod), Integrate with existing systems easily, streamline vehicle transportation tracking,
url: https://cdn.vehichaul.com
